### PR TITLE
added preloader

### LINKED ISSUE #28: Create a preloader for the website
Hey Opencoders! 

:thinking:  What you will need to know.
Basic HTML, CSS, Bootstrap

:clipboard:  Step by Step

* Read about basic HTML and bootstrap elements.[here is a tutorial ](https://www.w3schools.com/html/)
* Fork and then clone the repo.
* Edit the index.html file (create css files seperately if needed) and voila! 
* Use the name of the repo or the logo or animation for a unique preloader.

 :floppy_disk:  Commit your changes

 :twisted_rightwards_arrows:  Start a Pull Request. There are two ways how you can start a pull request:

* If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

* You can also edit files directly in your browser and open a pull request from there.  

:thinking:  Questions?
Leave a comment below!

### PR DESCRIPTION
**Pull request by naina24**
28 

Fixes #28

#### Short description of what this resolves:

added preloader

#### Changes proposed in this pull request and/or Screenshots of changes:
Screenshot (36)

-
-
-

### CODE REVIEW

**Comment by Archies11** [comment]
Add a live link of your work

**Comment by naina24** [comment]
https://condescending-archimedes-5ba974.netlify.com/

**Comment by naina24** [comment]
Actually gif is not getting fitted

**Comment by Archies11** [comment]
I am unable to understand how the preloader is supposed to look. The timer for the same is also not correct.

**Pull request closed without merging**
