### PR TITLE
33#

### LINKED ISSUE #33: Add a footer to the website
Hey Opencoders! 

:thinking:  What you will need to know.
Basic HTML, CSS, Bootstrap

:clipboard:  Step by Step

* Read about basic HTML and bootstrap elements.[here is a tutorial ](https://www.w3schools.com/html/)
* Fork and then clone the repo.
* Edit the index.html file (create css files seperately if needed) and voila! 
* Refer to existing websites for reference

 :floppy_disk:  Commit your changes

 :twisted_rightwards_arrows:  Start a Pull Request. There are two ways how you can start a pull request:

* If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

* You can also edit files directly in your browser and open a pull request from there.  

:thinking:  Questions?
Leave a comment below!

### PR DESCRIPTION
**Pull request by CadencePrestissimo**
__33__ 

Fixes #33

#### Short description of what this resolves:

added footer 
with social icons
Screenshot from 2020-01-26 18-56-16

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Archies11** [comment]
Add a live link of the changes you have made.

**Comment by pavikachaudhary** [comment]
https://focused-poitras-40cc64.netlify.com/

**Comment by CadencePrestissimo** [comment]
Final website:    https://cranky-blackwell-99022c.netlify.com/

**Comment by Archies11** [comment]
The footer of the website should only be visible when website is scrolled down. make changes for the same.

**Comment by pavikachaudhary** [comment]
https://youthful-easley-5830da.netlify.com/

**Comment by CadencePrestissimo** [comment]
https://youthful-easley-5830da.netlify.com/

**Pull request merged**
