### PR TITLE
landing page designed

### LINKED ISSUE #20: Create an attractive landing page for the website
Hey Opencoders! 

:thinking:  What you will need to know.
Basic HTML, CSS, Bootstrap

:clipboard:  Step by Step

* Read about basic HTML and bootstrap elements.[here is a tutorial ](https://www.w3schools.com/html/)
* Fork and then clone the repo.
* Edit the index.html file (create css files seperately if needed) and voila! 
* Use gradients, images etc foe the landing page. 

 :floppy_disk:  Commit your changes

 :twisted_rightwards_arrows:  Start a Pull Request. There are two ways how you can start a pull request:

* If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

* You can also edit files directly in your browser and open a pull request from there.  

:thinking:  Questions?
Leave a comment below!

### PR DESCRIPTION
**Pull request by rishika8910**
__20__ 

Fixes #20 

#### Short description of what this resolves:

designs the landing page

#### Changes proposed in this pull request and/or Screenshots of changes:
   
desktop
desktop2

#### Add a Github pages link of the changes you have made
https://rishika8910.github.io/Code-like-a-Girl/

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@rishika8910 There are a lot of file changes which are not required can you remove the files not required ..check the files changed tab of your pull request to get an idea of the same

**Comment by rishika8910** [comment]
ok ma.am I will just see to it

**Comment by rishika8910** [comment]
ma'am I have made the changes 
Do I need to create the pull request again?

**Comment by Archies11** [comment]
@rishika8910

**Comment by rishika8910** [comment]
> @rishika8910
ma'am do I need to create pull request?

**Comment by Archies11** [comment]
change the location of the nav bar back to the top. landing page has a scrollbar..remove that as well

**Comment by rishika8910** [comment]
> change the location of the nav bar back to the top. landing page has a scrollbar..remove that as well

ma'am how to shift the menu bar to the top as it is being hidden when I remove the scroll bar

**Comment by Archies11** [comment]
there must be some problem with the code. try to find it.
i would suggest not to tamper much with the existing code and simply adding your background.

**Comment by Archies11** [comment]
Closing PR due to inactivity.

**Pull request closed without merging**
