### PR TITLE
added preloader

### LINKED ISSUE #28: Create a preloader for the website
Hey Opencoders! 

:thinking:  What you will need to know.
Basic HTML, CSS, Bootstrap

:clipboard:  Step by Step

* Read about basic HTML and bootstrap elements.[here is a tutorial ](https://www.w3schools.com/html/)
* Fork and then clone the repo.
* Edit the index.html file (create css files seperately if needed) and voila! 
* Use the name of the repo or the logo or animation for a unique preloader.

 :floppy_disk:  Commit your changes

 :twisted_rightwards_arrows:  Start a Pull Request. There are two ways how you can start a pull request:

* If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

* You can also edit files directly in your browser and open a pull request from there.  

:thinking:  Questions?
Leave a comment below!

### PR DESCRIPTION
**Pull request by naina24**
28 

Fixes #28 

#### Short description of what this resolves:
preloader for the website is added

#### Changes proposed in this pull request and/or Screenshots of changes:
Screenshot (33)

-
-
-

#### Add a Github pages link of the changes you have made
https://eloquent-turing-1ecff9.netlify.com/

### CODE REVIEW

**Comment by Archies11** [comment]
THe preloader appears at the side of the screen. Shift it to the centre and make it more attractive.Use the logo or the name of the website for the same.

**Comment by Archies11** [comment]
Pull the changes made in the repo and add your content according to the new bootstrap version links .

**Comment by Archies11** [comment]
Updates?

**Comment by Archies11** [comment]
Closed due to inactivity

**Comment by naina24** [comment]
Ma'am I have almost animated the logo of code like a girl. Only I have to
push it. Please open it ma'am.

**Comment by Archies11** [comment]
Updates??
Push your commits and resolve merge conflicts ASAP

**Comment by Archies11** [comment]
This PR will be closed by the end of the day due to inactivity.

**Pull request closed without merging**
