### PR TITLE
Added go to top button

### LINKED ISSUE #42: Add button to jump to the landing page of the website.
Add a 'move to top' button when user scrolls through the website.

### PR DESCRIPTION
**Pull request by ananya-mohanty**
__42__

Fixes #42 

#### Short description of what this resolves:
Since there's not enough text, the go to top button isn't visible.

Added some text temporarily to show the same

#### Changes proposed in this pull request and/or Screenshots of changes:

-
Screenshot 2020-01-24 at 11 44 50 PMop

-
-

### CODE REVIEW

**Comment by Archies11** [comment]
Please add a live link of your work. This makes the PR easy to review.

**Comment by ananya-mohanty** [comment]
Live Link : https://ananya-mohanty.github.io/Code-like-a-Girl/

**Comment by Archies11** [comment]
The live link does not work.

**Comment by ananya-mohanty** [comment]
Please check again since I added some random text to make the button visible

**Pull request merged**
