### PR TITLE
added about page

### LINKED ISSUE #30: Add an about section for the website
Hey Opencoders! 

:thinking:  What you will need to know.
Basic HTML, CSS, Bootstrap

:clipboard:  Step by Step

* Read about basic HTML and bootstrap elements.[here is a tutorial ](https://www.w3schools.com/html/)
* Fork and then clone the repo.
* Edit the index.html file (create css files seperately if needed) and voila! 

 :floppy_disk:  Commit your changes

 :twisted_rightwards_arrows:  Start a Pull Request. There are two ways how you can start a pull request:

* If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

* You can also edit files directly in your browser and open a pull request from there.  

:thinking:  Questions?
Leave a comment below!

### PR DESCRIPTION
**Pull request by CadencePrestissimo**
__30__ 

Fixes #30
#### Short description of what this resolves:

Added an about section
Wrote about Code-like-a-Girl

#### Changes proposed in this pull request and/or Screenshots of changes:
There was a ;) at the end of webpage ,I removed that.
Added a about page also
-
-
-
Screenshot from 2020-01-22 03-29-12

### CODE REVIEW

**Comment by Archies11** [comment]
The live link does not render the bootstrap template used

**Comment by Archies11** [comment]
Clone the repo again and add your content according to the new bootstrap version links .

**Comment by Archies11** [comment]
Pull the changes made in the repo and add your content according to the new bootstrap version links .

**Comment by Archies11** [comment]
Updates?

**Comment by CadencePrestissimo** [comment]
Screenshot from 2020-01-25 16-53-33






https://amazing-bell-2c9144.netlify.com

**Comment by Archies11** [comment]
Attach a live link

**Comment by Archies11** [comment]
Attach the link.your pr might be closed due to inactivity

**Comment by CadencePrestissimo** [comment]
already attached in the previous comment

**Comment by Archies11** [comment]
The link does not display your changes. check the branch you have deployed.

**Comment by Archies11** [comment]
About page is simply a section of the website and not a separate page of its own. This is a single page scroll able website with various different sections.

**Comment by CadencePrestissimo** [comment]
https://gifted-torvalds-7651ed.netlify.com

**Comment by Archies11** [comment]
The heading for the about section is not centered. correct the placement. Also, link the nav bar item to about section. Add about section above the contributors. good effort though :)

**Comment by Archies11** [comment]
Updates?

**Comment by CadencePrestissimo** [comment]
working , will complete it by tomorrow morning,

**Comment by CadencePrestissimo** [comment]
https://compassionate-ptolemy-57043d.netlify.com/

**Pull request merged**
